---
- name: Configure workspace for tasks
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    - ancestor_project: "final-ancestor"
    - ancestor_source: "/projects/{{ ancestor_project }}"
  tasks:
    - name: Set facts from environmental variables
      ansible.builtin.set_fact:
        project_source: "{{ lookup('ansible.builtin.env', 'PROJECT_SOURCE') }}"

    - name: Environment variables copy PROJECT_SOURCE to SECONDARY_SOURCE
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export SECONDARY_SOURCE='
        line: export SECONDARY_SOURCE='{{ project_source }}'

    - name: Set MOLECULE_SCENARIO environment variables
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export MOLECULE_SCENARIO='
        line: export MOLECULE_SCENARIO='default'

    - name: Set ANCESTOR_SOURCE environment variables
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export ANCESTOR_SOURCE='
        line: "export ANCESTOR_SOURCE='{{ ancestor_source }}'"

    - name: Add file exclude to .code-workspace file
      ansible.builtin.script: "{{ ancestor_source }}/scripts/cw_add_file_exclude.py"
      args:
        executable: python3
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc > 1